import { vi } from 'vitest';

Element.prototype.animate = vi.fn(() => ({
  cancel: vi.fn(),
  finish: vi.fn(),
  pause: vi.fn(),
  play: vi.fn(),
  reverse: vi.fn(),
  persist: vi.fn(),
  updatePlaybackRate: vi.fn(),
  commitStyles: vi.fn(),
  currentTime: 0,
  effect: null,
  finished: Promise.resolve(),
  id: '',
  oncancel: null,
  onfinish: null,
  onremove: null,
  pending: false,
  playState: 'finished' as AnimationPlayState,
  playbackRate: 1,
  ready: Promise.resolve(),
  replaceState: 'active' as AnimationReplaceState,
  startTime: 0,
  timeline: null,
  addEventListener: vi.fn(),
  removeEventListener: vi.fn(),
  dispatchEvent: vi.fn(),
})) as any;
